# Claude Code Open Configuration
# Generate this file with: cco config generate

# Server configuration
host: 127.0.0.1                # Host to bind to
port: 6970                     # Port to listen on
api_key: sk-api-00-XXXYYYZZZ   # Optional: API key to protect the proxy

# Provider configurations
providers:
  # OpenRouter - Access to multiple models from different providers
  - name: openrouter
    api_key: your-openrouter-api-key
    # url: https://openrouter.ai/api/v1/chat/completions  # Optional: URL is set automatically
    model_whitelist:       # Optional: restrict to specific model patterns
      - claude             # Allow any model containing "claude"
      - gpt-4              # Allow any model containing "gpt-4"
    # default_models are set automatically based on provider

  # OpenAI - Direct access to GPT models
  - name: openai
    api_key: your-openai-api-key
    model_whitelist: ["gpt-4"]
    default_models:
      - babbage-002
      - dall-e-2
      - dall-e-3
      - davinci-002
      - gpt-3.5-turbo
      - gpt-3.5-turbo-0125
      - gpt-3.5-turbo-1106
      - gpt-3.5-turbo-16k
      - gpt-3.5-turbo-instruct
      - gpt-3.5-turbo-instruct-0914
      - gpt-4.1
      - gpt-4.1-2025-04-14
      - gpt-4.1-mini
      - gpt-4.1-mini-2025-04-14
      - gpt-4.1-nano
      - gpt-4.1-nano-2025-04-14
      - gpt-4o
      - gpt-4o-2024-05-13
      - gpt-4o-2024-08-06
      - gpt-4o-2024-11-20
      - gpt-4o-audio-preview
      - gpt-4o-audio-preview-2024-10-01
      - gpt-4o-audio-preview-2024-12-17
      - gpt-4o-audio-preview-2025-06-03
      - gpt-4o-mini
      - gpt-4o-mini-2024-07-18
      - gpt-4o-mini-audio-preview
      - gpt-4o-mini-audio-preview-2024-12-17
      - gpt-4o-mini-search-preview
      - gpt-4o-mini-search-preview-2025-03-11
      - gpt-4o-mini-transcribe
      - gpt-4o-mini-tts
      - gpt-4o-search-preview
      - gpt-4o-search-preview-2025-03-11
      - gpt-4o-transcribe
      - gpt-image-1
      - o1-mini
      - o1-mini-2024-09-12
      - omni-moderation-2024-09-26
      - omni-moderation-latest
      - text-embedding-3-large
      - text-embedding-3-small
      - text-embedding-ada-002
      - tts-1
      - tts-1-1106
      - tts-1-hd
      - tts-1-hd-1106
      - whisper-1
    # All GPT models will be available by default

  # Anthropic - Direct access to Claude models  
  - name: anthropic
    api_key: your-anthropic-api-key
    default_models:
      - claude-3-5-haiku-20241022
      - claude-3-5-sonnet-20240620
      - claude-3-5-sonnet-20241022
      - claude-3-7-sonnet-20250219
      - claude-3-haiku-20240307
      - claude-opus-4-20250514
      - claude-sonnet-4-20250514

  # Nvidia - Access to Nemotron models
  - name: nvidia
    api_key: your-nvidia-api-key

  # Google Gemini - Access to Gemini models
  - name: gemini
    api_key: your-gemini-api-key

# Router configuration for different use cases
router:
  default: openrouter/anthropic/claude-3.5-sonnet           # Default model
  think: openai/o1-preview                                   # For complex reasoning
  background: anthropic/claude-3-haiku-20240307             # For background tasks
  long_context: anthropic/claude-3-5-sonnet-20241022        # For long documents
  web_search: openrouter/perplexity/llama-3.1-sonar-huge-128k-online  # For web search

# Features:
# - YAML takes precedence over JSON configuration
# - Default URLs are set automatically for all providers
# - Default models are populated for each provider
# - Model whitelist allows filtering available models
# - All 5 major LLM providers are supported
# - Proxy can be protected with an API key
# - Different models can be configured for different use cases
